const https = require(`https`);
const fs = require('fs');
const path = require('path');
const process = require('process');

const customTlds = [
  'mail-tester.com',
];

async function main() {
  console.info('Downloading list');
  const payload = await new Promise((resolve, reject) => {
    const data = [];
    https.request('https://publicsuffix.org/list/public_suffix_list.dat', (res) => {
      res.on('data', (chunk) => data.push(chunk));
      res.on('error', (error) => reject(error));
      res.on('end', () => resolve(Buffer.concat(data).toString('utf8')));
    }).end();
  });
  const tlds = payload.split('\n').map((line) => line.trim()).filter(
    (line) => line && !line.startsWith('//')
  );
  console.info('Updating lib/tlds-autogenerated.json');
  fs.writeFileSync(
    path.join(__dirname, '..', 'lib', 'tlds-autogenerated.json'),
    JSON.stringify([...tlds, ...customTlds].sort(), null, 2)
  );
  console.info('Done');
}

if (require.main === module) {
  void main().catch((error) => {
    console.error(`Failed: ${error.stack || error}`);
    process.exit(-1);
  });
}
